// Export pages
export '/pages/patient/patient_main_page/patient_main_page_widget.dart'
    show PatientMainPageWidget;
export '/pages/patient/description_medecins/description_medecins_widget.dart'
    show DescriptionMedecinsWidget;
export '/pages/patient/appointemen_list/appointemen_list_widget.dart'
    show AppointemenListWidget;
export '/pages/patient/list_ordonance/list_ordonance_widget.dart'
    show ListOrdonanceWidget;
export '/pages/admin/dashboard_admin/dashboard_admin_widget.dart'
    show DashboardAdminWidget;
export '/pages/admin/creat_iion_patient/creat_iion_patient_widget.dart'
    show CreatIionPatientWidget;
export '/pages/admin/edit_patient/edit_patient_widget.dart'
    show EditPatientWidget;
export '/pages/admin/creat_doctores/creat_doctores_widget.dart'
    show CreatDoctoresWidget;
export '/pages/admin/profile_admin/profile_admin_widget.dart'
    show ProfileAdminWidget;
export '/pages/authentication/login_page/login_page_widget.dart'
    show LoginPageWidget;
export '/pages/authentication/the_start_page/the_start_page_widget.dart'
    show TheStartPageWidget;
export '/pages/patient/profile_patient/profile_patient_widget.dart'
    show ProfilePatientWidget;
export '/pages/admin/list_medcines/list_medcines_widget.dart'
    show ListMedcinesWidget;
export '/pages/admin/listes_patient/listes_patient_widget.dart'
    show ListesPatientWidget;
export '/pages/medecin/edit_doctors/edit_doctors_widget.dart'
    show EditDoctorsWidget;
export '/pages/medecin/dashboard_medecin/dashboard_medecin_widget.dart'
    show DashboardMedecinWidget;
export '/pages/medecin/liste_patients/liste_patients_widget.dart'
    show ListePatientsWidget;
export '/pages/medecin/creer_ordonnance/creer_ordonnance_widget.dart'
    show CreerOrdonnanceWidget;
export '/pages/medecin/liste_ordonnances/liste_ordonnances_widget.dart'
    show ListeOrdonnancesWidget;
export '/pages/medecin/dossier_medical/dossier_medical_widget.dart'
    show DossierMedicalWidget;
export '/pages/medecin/lister_rendezvous/lister_rendezvous_widget.dart'
    show ListerRendezvousWidget;
export '/pages/medecin/notifications/notifications_widget.dart'
    show NotificationsWidget;
export '/pages/patient/notification_patientt/notification_patientt_widget.dart'
    show NotificationPatienttWidget;
export '/pages/patient/creer_rendue_vouz/creer_rendue_vouz_widget.dart'
    show CreerRendueVouzWidget;
export '/pages/admin/update_password_admin/update_password_admin_widget.dart'
    show UpdatePasswordAdminWidget;
export '/pages/medecin/update_password_medecin/update_password_medecin_widget.dart'
    show UpdatePasswordMedecinWidget;
export '/pages/patient/update_password_patient/update_password_patient_widget.dart'
    show UpdatePasswordPatientWidget;
export '/pages/testing/crud/crud_widget.dart' show CrudWidget;
export '/pages/medecin/profile_med/profile_med_widget.dart'
    show ProfileMedWidget;
export '/pages/medecin/edit_profile_med/edit_profile_med_widget.dart'
    show EditProfileMedWidget;
